name: Devtools CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8 # Node 16 supports up to pnpm v8

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set COMMIT_SHA
        shell: bash
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
          else
            echo "COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}

      - name: Run tests
        run: |
          pnpm test
          pnpm run test:e2e
